### ISSUE TITLE
dccon_list.js 파일 형식

### ISSUE THREAD

**Issue by rishubil** [krynen/yeokka#5]
안녕하세요, [yeokka/dccon/dccon_list.js](https://github.com/krynen/yeokka/blob/6a98edd7e259706ab7f420eede97ae6bdaadc4f9/dccon/dccon_list.js) 파일 형식에 대해 문의드립니다.

현재 `yeokka/dccon/dccon_list.js` 파일은 yeokka님 방송과 @hibiyasleep 님이 디시콘 기능을 제공하는 일부 방송에서 사용하고 있는 디시콘 데이터 형식으로 알고 있습니다.

이에 따라, [Open Dccon Selector](https://github.com/rishubil/open-dccon-selector)에서 제공하는 디시콘 데이터 형식 변환 기능에서 해당 파일 형식을 지원하고자 합니다.

디시콘 데이터 형식 변환 기능은 현재 개발중인 트위치 익스텐션 Open Dccon Selector와 크롬 익스텐션 [Twitch DCCON extension](https://chrome.google.com/webstore/detail/twitch-dccon-extension/nljojmgmnidbehhocgkbeejchcmkpgki)에 디시콘 데이터를 전달하기 위한 API의 일부로, 여러 [디시콘 데이터 형식](https://github.com/rishubil/open-dccon-selector/blob/master/CONFIG.ko.md#21-%EC%A7%80%EC%9B%90%ED%95%98%EB%8A%94-dccon-type)을 Open Dccon Format으로 변환하여 제공하는 기능입니다.

기능 추가에 앞서,

1. 해당 파일 형식을 부를 명칭과
1. 근시일 내에 데이터 구조 변경이 계획되어 있는지

알고 싶습니다.

**Comment by krynen** [comment]
1. 채팅 오버레이 시스템 명칭이 bridge BBCC (beta)이니 적당히 써주시면 될 것 같습니다.

2. 버전업과 함께 변경할 계획은 대략 되어있으나 확정된 부분은 없고,
변경하더라도 제 측에서 JSAssist Open Dccon용 .json포맷으로 변환하는 기능을 같이 제공할 듯 합니다.

**Comment by hibiyasleep** [comment]
나중에 제 채팅창 구현에서 랜덤 키워드 *(ex: `~빠요엔`을 입력하면 빠요엔1~3 중 하나가 튀어나옴)* 기능이 생길 수도 있고 안 생길 수도 있습니다만, 일단 변경되더라도 JSAssist Open Dccon용 호환 포맷을 제공할 예정입니다.

**Comment by rishubil** [comment]
흑흑 호환 포멧이라니 감사합니다. 그럼 현재 포멧은 임시로만 지원하도록 하겠습니다.
