### ISSUE TITLE
Mobile tgd 환경에서 제목과 카테고리 간의 구분이 되지 않습니다.

### ISSUE THREAD

**Issue by kyujin-cho** [krynen/yeokka#9]
<img width="515" alt="image" src="https://user-images.githubusercontent.com/2904494/39567058-a9368096-4ef8-11e8-9ce5-6e62823f30f0.png">
제목 혹은 카테고리 둘중 하나의 글씨 색을 바꿔야 할 듯 합니다. 

<img width="423" alt="image" src="https://user-images.githubusercontent.com/2904494/39567107-d4c90d1e-4ef8-11e8-8dab-96b9426778b6.png">
트게더 게시판 구조를 제가 잘 모르는데, 카테고리(span.category)에 style로 color가 하드코딩 되어 있는 거 보면 카테고리 색은 바꾸면 안 되는 것인가요?

**Comment by krynen** [comment]
카테고리 색은 카테고리 종류별로 해당 트게더 스트리머가 직접 설정하게 되어 있습니다.
다시말해 여까님이 직접 설정하신 부분이라는 거..

대신 PC환경에서와 같이 점선으로 구분하게끔 처리했습니다.

**Comment by kyujin-cho** [comment]
감사합니다.
